// @ts-nocheck
"use client"
import './globals.css'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'

const ProtectedRoutes = dynamic(() => import('./ProtectedRoutes'), { ssr: false })
const Navbars = dynamic(() => import('@/components/navbar'), { ssr: false })



import { Inter } from 'next/font/google'
import ReduxProvider from '@/redux/provider'
// import Navbars from '@/components/navbar'
// import ProtectedRoutes from './ProtectedRoutes'


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="es">
      <body className={inter.className}>
        <ReduxProvider>
          <ProtectedRoutes>
            <Navbars />

            <main>{children}</main>
          </ProtectedRoutes>
        </ReduxProvider>
      </body>
    </html>
  )
}
